### ISSUE TITLE
TenantLineInnerInterceptor使用报异常

### ISSUE THREAD

**Issue by lizhichao999** [baomidou/mybatis-plus-samples#60]
org.springframework.web.util.NestedServletException: Handler dispatch failed; nested exception is java.lang.NoSuchMethodError: net.sf.jsqlparser.statement.select.PlainSelect.getGroupByColumnReferences()Ljava/util/List;
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1055)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:943)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:909)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:652)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:733)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at com.github.xiaoymin.knife4j.spring.filter.ProductionSecurityFilter.doFilter(ProductionSecurityFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)

同时存在：  LambdaUpdateWrapper<ItmsTaskInfo> updateWrapper = new LambdaUpdateWrapper<>();
        updateWrapper.set(ItmsTaskInfo::getExceptionStatus, ExceptionStatusEnum.EXCEPTION.getCode())
            .set(ItmsTaskInfo::getModifiedBy,currUserName)
            .set(ItmsTaskInfo::getGmtModified,utc8Date)
            .eq(ItmsTaskInfo::getId, itmsTaskInfo.getId());
        this.baseMapper.update(null, updateWrapper);

2种都满足如何接，现在情况是满足一个另外一个就报错

**Comment by lizhichao999** [comment]
Caused by: java.lang.NoSuchMethodError: net.sf.jsqlparser.statement.select.PlainSelect.getGroupByColumnReferences()Ljava/util/List;
	at com.github.pagehelper.parser.CountSqlParser.isSimpleCount(CountSqlParser.java:156)
	at com.github.pagehelper.parser.CountSqlParser.sqlToCount(CountSqlParser.java:135)
	at com.github.pagehelper.parser.CountSqlParser.getSmartCountSql(CountSqlParser.java:94)
	at com.github.pagehelper.dialect.AbstractHelperDialect.getCountSql(AbstractHelperDialect.java:81)
	at com.github.pagehelper.PageHelper.getCountSql(PageHelper.java:77)
	at com.github.pagehelper.PageInterceptor.executeAutoCount(PageInterceptor.java:193)
	at com.github.pagehelper.PageInterceptor.intercept(PageInterceptor.java:113)
	at org.apache.ibatis.plugin.Plugin.invoke(Plugin.java:61)
	at com.sun.proxy.$Proxy214.query(Unknown Source)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:147)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:140)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:426)
	at com.sun.proxy.$Proxy115.selectList(Unknown Source)
